# web server installation
- hosts: webserver
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: ensure httpd is running
      service:
        name : httpd
        state : started
  
#database installation
- hosts: database
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install and execute postgresql
      shell: |
        rpm -Uvh https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum install -y postgresql11-server postgresql11-contrib
        /usr/pgsql-11/bin/postgresql-11-setup initdb
        systemctl enable postgresql-11.service
        systemctl start postgresql-11.service